name: wott-agent
version: '0.1.5.0-18'
summary: Web of Trusted Things agent.
description: |
  tl;dr - WoTT Agent is the Let's Encrypt for IoT.
grade: stable
confinement: strict
base: core18
architectures:
  - armhf
  - arm64
  - amd64
  - i386

apps:
  daemon:
    command: wott-agent
    daemon: oneshot
    plugs:
      - firewall-control
      - hardware-observe
      - network
      - network-observe
      - tpm
    passthrough:
      timer: 00:00-24:00/24

  wott-agent:
    command: wott-agent
    plugs:
      - network
      - network-observe

  ghostunnel:
    command: ghostunnel
    plugs:
      - network
      - network-bind

  server:
    command: server.sh
    plugs:
      - network
      - network-bind

  client:
    command: client.sh
    plugs:
      - network
      - network-bind

  whoami:
    command: python3 -c 'import agent; print(agent.get_device_id())'

  verify-cert:
    command: openssl verify -CAfile "$SNAP_DATA/ca.crt" "$SNAP_DATA/client.crt"

  inspect-cert:
    command: openssl x509 -in "$SNAP_DATA/client.crt" -text -noout

  test-cert:
    command: python3 -c 'import agent; print(agent.say_hello())'

  portscan:
    command: python3 -c 'import agent; print(agent.get_open_ports())'

slots:
  wott-certs:
    content: wott-certs
    interface: content
    read:
      - $SNAP_DATA

parts:
  wott-agent:
    plugin: python
    python-version: python3
    source: https://github.com/GreatFruitOmsk/agent.git
    requirements:
      - requirements.txt
    source-type: git
    source-branch: fix-snap
    build-packages:
      - python3-git
      - libffi-dev
      - libffi6
      - libssl-dev
      - pkg-config
      - libsystemd0
      - libsystemd-dev
    stage-packages:
      - iptables

  ghostunnel:
    plugin: go
    go-importpath: github.com/square/ghostunnel
    source: .
    source-tag: v1.3.0
    build-packages:
      - build-essential
    stage-packages:
      - libltdl-dev

